import { PipeType, PipeRotation } from "../types/pipe_types";

// По задумке механики игры первая труба всегда тип CROSS, а последняя STRAIGHT
export const GAME_CONFIG = [
    {
        gridSize: { width: 8, height: 6 },
        pipes: [
            [
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
            ],
            [
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_180 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_180 },
            ],
            [
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_270 },
            ],
            [
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_180 },
            ],
            [
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_90 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_270 },
            ],
            [
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
            ]
        ]
    },
    {
        gridSize: { width: 10, height: 10 },
        pipes: [
            [
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
            ],
            [
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_180 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
            ],
            [
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
            ],
            [
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_180 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
            ],
            [
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_90 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
            ],
            [
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_270 },
            ],
            [
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
            ],
            [
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
            ],
            [
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_180 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
            ]
        ]
    },
    {
        gridSize: { width: 9, height: 15 },
        pipes: [
            [
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
            ],
            [
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_180 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
            ],
            [
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
            ],
            [
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_180 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
            ],
            [
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_90 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_180 },
            ],
            [
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
            ],
            [
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
            ],
            [
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
            ],
            [
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_180 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
            ],
            [
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
            ],
            [
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_180 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
            ],
            [
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_90 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_180 },
            ],
            [
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
            ],
            [
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
            ],
            [
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
            ],
            [
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_180 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_180 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_0 },
            ],
            [
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_270 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
            ]
        ]
    },
    {
        gridSize: { width: 12, height: 7 },
        pipes: [
            [
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_180 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
            ],
            [
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_90 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_180 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_90 },
            ],
            [
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_270 },
            ],
            [
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_180 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
            ],
            [
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_180 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
            ],
            [
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_180 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
            ],
            [
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
            ],
        ]
    },
    {
        gridSize: { width: 15, height: 9 },
        pipes: [
            [
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_180 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_180 },
            ],
            [
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_180 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
            ],
            [
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_180 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
            ],
            [
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_180 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
            ],
            [
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_180 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
            ],
            [
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_180 },
            ],
            [
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_180 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
            ],
            [
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_180 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
            ],
            [
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_180 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_180 },
            ],
            [
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.CROSS, rotation: PipeRotation.DEG_270 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_180 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.T_SHAPE, rotation: PipeRotation.DEG_90 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_270 },
                { type: PipeType.CURVED, rotation: PipeRotation.DEG_0 },
                { type: PipeType.STRAIGHT, rotation: PipeRotation.DEG_90 },
            ],
        ]
    },
];
